### ISSUE TITLE
using CSL JSON file with addbibresource

### ISSUE THREAD

**Issue by jpjoines** [zepinglee/citeproc-lua#11]
Is it possible to use a CSL JSON file directly with \addbibresource{}?  Is it even a good idea?  I think it could eliminate one potentially lossy references conversion in my workflow.

I'm working with Zotero/Better BibTeX to translate my Zotero references to Bib(La)Tex format.  Then using citeproc-lua via the citation-style-language LaTeX package to enable use of CSL styles in my LaTeX documents.  If I understand it correctly, citeproc-lua converts from BibTeX to CSL JSON internally.

Zotero/Better BibTeX can export directly from Zotero to CSL JSON (and other formats like YAML, etc., https://github.com/retorquere/zotero-better-bibtex/tree/master/translators).  If citeproc-lua/citation-style-language.sty could use the JSON file directly, it could cut out one format conversion.

**Comment by zepinglee** [comment]
Yes, it totally makes sense. And I'm planning to make CSL-JSON the preferred format.

**Comment by zepinglee** [comment]
Thanks for your feedback!
