### ISSUE TITLE
context integration 

### ISSUE THREAD

**Issue by denismaier** [zepinglee/citeproc-lua#13]
Wow, that's an interesting project. Do you think a context integration would be feasible?

**Comment by bdarcus** [comment]
From a quick look, seems like yes, given that it hooks up at the (LuaTeX) engine level.

There'd just need to be some sort of ConTeXt layer on top of that.

@zepinglee - there's been talk about something like this for ConTeXt for years.

**Comment by zepinglee** [comment]
I have little experience with ConTeXt. I guess the the luaxml library that `citeproc-lua` depends on may need to be switched to the XML component of ConTeXt.

**Comment by bdarcus** [comment]
IUC, at this point, a lot of context is implemented in lua, and relies on luatex.
