### ISSUE TITLE
running citeproc does not produce a bbl file

### ISSUE THREAD

**Issue by denismaier** [zepinglee/citeproc-lua#16]
Running citeproc on the aux file does not produce a bbl file here. I don't get an error message, so I cannot really say more. All I can say is that the sequence mentioned in the readme doesn't do anything for me.

```
pdflatex test.tex
pdflatex test.aux
pdflatex test.tex
```

Using lualatex works though.

**Comment by zepinglee** [comment]
The TeX Live team mistakenly uses [citeproc/citeproc.lua](https://github.com/zepinglee/citeproc-lua/blob/main/citeproc/citeproc.lua) as the executable script which should be [latex/citeproc](https://github.com/zepinglee/citeproc-lua/blob/main/latex/citeproc). The former is expected to be used as a Lua library (`local citeproc = require("citeproc")`). I'll contact them to correct this.

**Comment by zepinglee** [comment]
The TeX Live team has fixed the binary name. 

Note that I've also renamed the executable from `citeproc` to `citeproc-lua` in order to avoid conflicts with citeproc implementations in other languages. Now the full compiling procedure for pdflatex or xelatex is:

```bash
pdflatex test.tex
citeproc-lua test.aux
pdflatex test.tex
```
