### ISSUE TITLE
Long cite not working

### ISSUE THREAD

**Issue by nickw2066** [zepinglee/citeproc-lua#20]
I can't seem to get a long citation to appear.
I'm using the turabian-fullnote-bibliography.csl file (standard CSL, no changes on my part).

I've attached a Word document and Word PDF to show that the long citation appears in Word (through Zotero, using the same style: Turabian 8th edition [full note]).
[testLongCiteWord.docx](https://github.com/zepinglee/citeproc-lua/files/9274601/testLongCiteWord.docx)
[testLongCiteWord.pdf](https://github.com/zepinglee/citeproc-lua/files/9274602/testLongCiteWord.pdf)

I've also attached the output PDF produced by lualatex.
[testLongCite.pdf](https://github.com/zepinglee/citeproc-lua/files/9274611/testLongCite.pdf)

Here is my tex file:
```tex
\documentclass[12pt]{article}

\usepackage{citation-style-language}
\cslsetup{style = turabian-fullnote-bibliography}
\addbibresource{myBib.json}

\begin{document}

Bruce Metzger said that.\cite{Metzger2005-TheTex}

\end{document}
```

Here is my JSON bibliography:
```json
[
    {
        "id": "Metzger2005-TheTex",
        "type": "book",
        "author": [
            {
                "family": "Metzger",
                "given": "Bruce M."
            },
            {
                "family": "Ehrman",
                "given": "Bart D."
            }
        ],
        "title": "The Text of the New Testament: Its Transmission, Corruption, and Restoration",
        "title-short": "Text of the New Testament",
        "edition": "4",
        "publisher-place": "New York, NY",
        "publisher": "Oxford University Press",
        "issued": {
            "date-parts": [
                [
                    "2005"
                ]
            ]
        }
    }
]
```

What am I doing wrong?

**Comment by zepinglee** [comment]
Thanks for your feedback! I can reproduce the bug. It seems that the `position = first / subsequent` logic is not handled correctly.

I've nearly finished rewriting the Lua processor and hope that will fix this bug.

**Comment by zepinglee** [comment]
This issue should be fixed now.
<img width="632" alt="Screen Shot 2022-08-12 at 12 50 21" src="https://user-images.githubusercontent.com/12290822/184318244-106299d3-51e5-483d-98c9-242e4e7c78a5.png">

**Comment by nickw2066** [comment]
Thank you so much for your work on this.
I would like to use the update, but my Tex Live app can’t see the update (because I suppose the update has not been released to CTAN). Are you able to tell me when the update will go through to CTAN, or point me to how I might use it before then?

**Comment by zepinglee** [comment]
It is because I have not published it to CTAN yet. I was orginally planning to make a larger update before releasing but I'm currently stuck with rewriting the BibTeX parser. I've changed my mind and prepare this release now.

**Comment by zepinglee** [comment]
I've just uploaded v0.2.0 to CTAN and it should be available to TeX Live soon.

**Comment by nickw2066** [comment]
Thank you—it’s all working for me now.
