### ISSUE TITLE
Cite in csquotes' blockquote not working

### ISSUE THREAD

**Issue by nickw2066** [zepinglee/citeproc-lua#21]
I'm note sure why this code won't compile:
```tex
\documentclass[12pt]{article}

\usepackage{citation-style-language}
\cslsetup{style = turabian-fullnote-bibliography}
\addbibresource{myBib.json}

\usepackage{csquotes}

\begin{document}

\blockquote{Bruce Metzger said that.\cite{Metzger2005-TheTex}\relax}

\end{document}
```

Here is my JSON file:
```json
[
    {
        "id": "Metzger2005-TheTex",
        "citation-key": "Metzger2005-TheTex",
        "type": "book",
        "author": [
            {
                "family": "Metzger",
                "given": "Bruce M."
            },
            {
                "family": "Ehrman",
                "given": "Bart D."
            }
        ],
        "title": "The Text of the New Testament: Its Transmission, Corruption, and Restoration",
        "title-short": "Text of the New Testament",
        "edition": "4",
        "publisher-place": "New York, NY",
        "publisher": "Oxford University Press",
        "issued": {
            "date-parts": [
                [
                    "2005"
                ]
            ]
        }
    }
]
```

The error given is:
`! Argument of \csq@getcargs@ii has an extra }.
<inserted text> 
\par 
l.11 ... said that.\cite{Metzger2005-TheTex}\relax}`

If you spot my error please let me know.

**Comment by nickw2066** [comment]
I'm getting another error (on compilation) with itemize and am wondering if it's related?
Here is my tex file:
`\documentclass[12pt]{article}

\usepackage{citation-style-language}
\cslsetup{style = turabian-fullnote-bibliography}
\addbibresource{myBib.json}

\begin{document}

\begin{itemize}
\item
Bruce Metzger said that.\cite{Metzger2005-TheTex}
\end{itemize}

\end{document}
`

The JSON file is the same as above.

The compilation error is:
`! Use of \@item doesn't match its definition.
\text@command #1->\edef \reserved@a {
                                     \unexpanded {#1}}\ifx \reserved@a \@emp...

l.11 ... Metzger said that.\cite{Metzger2005-TheTex}`

**Comment by zepinglee** [comment]
Thanks again! I can also reproduce the `csquote` compatibility error. I may need to dig into the implementation of `\blockquote` to resolve it.

**Comment by zepinglee** [comment]
<img width="466" alt="Screen Shot 2022-08-12 at 16 16 18" src="https://user-images.githubusercontent.com/12290822/184318295-23b71ba5-0226-4de0-8de3-13df89ef47c7.png">
<img width="647" alt="Screen Shot 2022-08-12 at 16 16 21" src="https://user-images.githubusercontent.com/12290822/184318308-18044841-573a-45d8-8d37-0e2c25062166.png">

It should work as expected now. The `itemize` issue has also been resolved.
