### ISSUE TITLE
Document how to install the github version on top of the version onstalled by TeXLive

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [zepinglee/citeproc-lua#23]
Perusing the project history shows that it evolves (and progresses) much faster than TeXLive (especially distribution-packaged versions of TeXLive...). However, how to to replace the TeXLive verison to the last Github version isn't absolutely obvious to the LaTeX end-user who would like to use the corrected/expanded/new features without diving in the finesses of Lua unit testing...

A small paragraph explaining how to install/uninstall rhe github version on top of TeXLive-installed one would be welcome...

**Comment by EmmanuelCharpentier** [comment]
Never mind : I managed to get the answer from my distro's (Debian) documentation ... and renounced the idea (too much work). I'll wait fot he next distro package upgrade.

**Comment by zepinglee** [comment]
Thanks for your feedback and the suggestion makes sense.

There is a simple description about installing the develop version in <https://github.com/zepinglee/citeproc-lua/tree/main/example> and I'll add it later to the PDF documentation and repository README.

> Never mind : I managed to get the answer from my distro's (Debian) documentation ... and renounced the idea (too much work). I'll wait fot he next distro package upgrade.

Is there a link to the discussion? I have no awareness about the distribution-packaged version (like Debian) of TeX Live.
