### ISSUE TITLE
Modification of citeproc-bib.lua to support German umlaute

### ISSUE THREAD

**Issue by uttiES** [zepinglee/citeproc-lua#24]
Hey,

great project, thank you for sharing it! In order to use it for German references, I had to modify citeproc-bib.lua and thought you might be interested in my code as you left a "-- TODO: unicode chars like \"{o}" in bib.unescape. So here's my simple code inserted below that TODO:
  str = string.gsub(str, "\\\"o", "ö")
  str = string.gsub(str, "\\\"a", "ä")
  str = string.gsub(str, "\\\"u", "ü")
  str = string.gsub(str, "\\\"O", "Ö")
  str = string.gsub(str, "\\\"A", "Ä")
  str = string.gsub(str, "\\\"U", "Ü")

Additionally, I found that str = string.gsub(str, "\\%%", "%") leads to this error for some files: "...mf-dist/scripts/citation-style-language/citeproc-bib.lua:158: invalid use of '%' in replacement string", where line 158 is str = string.gsub(str, "\\%%", "%"). My quick fix was to simply comment it out, but I guess you can do better than me and maybe fix that issue? :)

Cheers

**Comment by zepinglee** [comment]
I've started working on this but it's more complicated than I expected because all patterns like `\"o`, `\"{o}`, `{\"o}`, `{\"{o}}` should be converted to `ö` and there a full list in <https://github.com/latex3/latex2e/blob/develop/base/utf8ienc.dtx>. I'm rewriting the whole BibTeX parser with `lpeg` to solve this issue.

This percent issue is a bug and it should be corrected: `str = string.gsub(str, "\\%%", "%%")`.

**Comment by zepinglee** [comment]
At the moment, the best practice is using Zotero with [`Better BibTeX`](https://retorque.re/zotero-better-bibtex/) (BBT) plugin: import the `.bib` database into Zotero and then export to CSL-JSON format. The BBT plugin is robust in `.bib` conversion.

**Comment by zepinglee** [comment]
I've rewritten the BibTeX parser with `lpeg` (c720941) and it should now convert LaTeX commands like `\"o` to Unicode correctly. Can you provide your `.bib` data for further testing?

**Comment by uttiES** [comment]
> @uttiES I've rewritten the BibTeX parser with `lpeg` ([c720941](https://github.com/zepinglee/citeproc-lua/commit/c72094107ab55ef66e707ce9241e3bc0d9a3f47f)) and it should now convert LaTeX commands like `\"o` to Unicode correctly. Can you provide your `.bib` data for further testing?

Oh so nice! Here's a short example exported from Zotero:

[Example.zip](https://github.com/zepinglee/citeproc-lua/files/9584023/Example.zip)

**Comment by zepinglee** [comment]
I've added it to [test/bibtex/issue-24.bib](https://github.com/zepinglee/citeproc-lua/blob/f34b2c6055a0ae4a825c95af0e8613cd3cfb6f41/test/bibtex/issue-24.bib) and it's converted to CSL-JSON correctly ([test/bibtex/issue-24.json](https://github.com/zepinglee/citeproc-lua/blob/f34b2c6055a0ae4a825c95af0e8613cd3cfb6f41/test/bibtex/issue-24.json)).
