### ISSUE TITLE
The cs:alternative extension seems to be not supported

### ISSUE THREAD

**Issue by kotobuki** [zepinglee/citeproc-lua#38]
Hi,

As a researcher and developer in Japan, I'm super happy to see that the [`cs:layout` extension](https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html#cs-layout-extension) of CSL-M has been supported in citeproc-lua. 🙇 I just confirmed that the feature works fine with a few CSL-M style files!

A missing feature is the [`cs:alternative` extension](https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html#cs-alternative-extension) such as `alt-translator`. Would you happen to have a plan to support the extension?

Here is an example of a bibliography item that contains `alt-translator`, `alt-issued`, `alt-publisher-place`, and `alt-publisher`.

```json
[
  {
    "id": "morgan2022philosophy",
    "author": [
      {
        "family": "Morgan",
        "given": "Casey"
      },
      {
        "family": "Patrov",
        "given": "Alexei"
      }
    ],
    "citation-key": "morgan2022philosophy",
    "event-place": "Chicago, IL",
    "issued": {
      "date-parts": [[2022]]
    },
    "language": "en>ja",
    "note": "alt-title: 自由意志の哲学\nalt-translator: 鈴木||真紀\nalt-issued: 2023\nalt-publisher-place: 東京\nalt-publisher: 城南大学出版会",
    "publisher": "Imaginary University Press",
    "publisher-place": "Chicago, IL",
    "title": "The Philosophy of Free Will",
    "type": "book"
  }
]
```

**Comment by zepinglee** [comment]
It seems that this feature is marked as deprecated. Is it still required by some Japanese styles?
