### ISSUE TITLE
Bug with AZR CSL Style: context.lua:70: attempt to index a nil value (field 'cite')

### ISSUE THREAD

**Issue by daniel-eder** [zepinglee/citeproc-lua#39]
**Describe the bug**
When trying to buid a .tex file using the example bib of the AZR csl style I run into the error "context.lua:70: attempt to index a nil value (field 'cite')". 

The sample bib can be found here: https://github.com/PhilippTh/austrian-legal-citation-style/blob/master/Beispiele/Beispiele.bib
In the below tex file the content is in a file "min.bib". 
The current official csl for AZR can be found here: https://github.com/citation-style-language/styles/blob/master/azr-abkurzungs-und-zitierregeln-der-osterreichischen-rechtssprache-und-europarechtlicher-rechtsquellen.csl
In the below example it is placed as "acr.csl" next to "example.tex"

The error does not happen for all bib entries. `zankl_kunstliche_2019` works, while `schweighofer_rechtsinformatik_1999` causes the error. A handful of other entries seem to work, while most others also cause it.

When clearing out the bib file and leaving e.g only `schweighofer_rechtsinformatik_1999` the issue remains.

For all entries that the error does not happen a correct pdf is created when running `lualatex example.tex` twice. 

**Additional information**
- TeX distribution: MiKTeX 23.5 with LuaLaTex Version 1.17.0
- Package `citation-style-language` version: 0.4.1
- LaTeX engine: `lualatex` [e.g. `pdflatex` / `xelatex` / `lualatex`]

**To Reproduce**
```tex
\documentclass{article}

\usepackage{citation-style-language} 
\usepackage{hyperref}

\addbibresource{min.bib}
\cslsetup{style = azr}

\newcommand\cs[1]{\texttt{\textbackslash #1}}
\pagestyle{empty}
\setlength{\parindent}{0pt}


\begin{document}

\section*{The standard \cs{cite} command}

\cite{schweighofer_rechtsinformatik_1999}

% Print the reference list
\printbibliography

\end{document}
```

**Screenshots**
N/A

**Comment by daniel-eder** [comment]
You are a lifesaver! Many thanks.
Will the issue close on next release or should I close it?

**Comment by zepinglee** [comment]
Just find your test case doesn't work with pdflatex. I'll fix it before making a release to CTAN.

You can close the issue when your local build passes.
