### ISSUE TITLE
Bug with lualatex and a nonbreakspace in the locale file

### ISSUE THREAD

**Issue by hvoss49** [zepinglee/citeproc-lua#42]
**Describe the bug**
running this with pdflatex or xelatex works fine.
But running with lualatex the `&#160;` in the file `csl-locales-de-DE.xml`
which should be a non breakable space is for lualatex a linebreak (see
image and the linebreak between u. a., which is et al in german).

If I change the `&#160;` to `&ThinSpace;` in the file `csl-locales-de-DE.xml`,
(line no 77 ,  localisation for et-al), then it works for lualatex, but
gives an error for pdflatex.

**Additional information**
- TeX distribution: [TeXLive 2023, MacTeX 2023]
- Package `citation-style-language` version: [e.g. v0.4.4]
- LaTeX engine: [e.g. `pdflatex` / `xelatex` / `lualatex`]

**To Reproduce**
```tex
\documentclass{article}
\usepackage{libertinus}
\usepackage[ngerman]{babel}
\usepackage[style=modern-language-association]{citation-style-language}
\addbibresource{biblatex-examples.bib}
\begin{document}
~\parencite{aksin}
\printbibliography
\end{document}
```

**Screenshots**
<img width="388" alt="Bildschirmfoto 2023-09-25 um 10 53 01" src="https://github.com/zepinglee/citeproc-lua/assets/12891199/4ee81e59-ae7d-4974-ba77-8017c01b4967">

**Comment by zepinglee** [comment]
Thanks for your bug report and I can reproduce it. However I can’t solve it in the first try. Currently I’m on vacation and I’ll loot at it again after returning home.Zeping Lee在 2023年9月26日，18:26，Herbert Voß ***@***.***> 写道：﻿
Describe the bug
running this with pdflatex or xelatex works fine.
But running with lualatex the   in the file csl-locales-de-DE.xml
which should be a non breakable space is for lualatex a linebreak (see
image and the linebreak between u. a., which is et al in german).
If I change the &#160; to &ThinSpace; in the file csl-locales-de-DE.xml,
(line no 77 ,  localisation for et-al), then it works for lualatex, but
gives an error for pdflatex.
Additional information

TeX distribution: [TeXLive 2023, MacTeX 2023]
Package citation-style-language version: [e.g. v0.4.4]
LaTeX engine: [e.g. pdflatex / xelatex / lualatex]

To Reproduce
\documentclass{article}
\usepackage{libertinus}
\usepackage[ngerman]{babel}
\usepackage[style=modern-language-association]{citation-style-language}
\addbibresource{biblatex-examples.bib}
\begin{document}
~\parencite{aksin}
\printbibliography
\end{document}
Screenshots

**Comment by zepinglee** [comment]
This problem can be reproduced with the following minimal code and it's explained in <https://tex.stackexchange.com/q/618254/82731>. I'm planning to use `tex.sprint("\\def...")` mentioned in the comment.

```tex
\documentclass{article}

\usepackage{luacode}
% \usepackage[ngerman]{babel}

\begin{document}

\def\foo{}
\begin{luacode*}
  token.set_macro("foo", "u.~a.")
\end{luacode*}
% \show\foo
\foo

\end{document}
```

<img width="54" alt="Screenshot 2023-10-02 at 12 22 54" src="https://github.com/zepinglee/citeproc-lua/assets/12290822/f19264c9-a8c7-42df-ab4a-8fbdd1386ad2">

**Comment by zepinglee** [comment]
> If I change the `&#160;` to `&ThinSpace;` in the file `csl-locales-de-DE.xml`, (line no 77 , localisation for et-al), then it works for lualatex, but gives an error for pdflatex.

The citeproc-lua has a limited method to convert unicode to LaTeX and thin space is kept in the unicode form. Since this code point is not defined in `utf8enc.dfu`, it's not accepted by pdftex. How about converting it to `\thinspace{}`?

https://github.com/zepinglee/citeproc-lua/blob/e31cbe8b2156480e3557c93f5ead45eb59658c48/citeproc/citeproc-output.lua#L1761-L1770
