### ISSUE TITLE
default for no defined style

### ISSUE THREAD

**Issue by hvoss49** [zepinglee/citeproc-lua#43]
If no style is defined we get the _warning_ message

    Package citation-style-language Warning: Style name not specified.

which is okay. But it is more user-friendly if it could use a default style, apa or whatever:

        Package citation-style-language Warning: Style name not specified.
        Will use default style apa ...

The problem is that the _warning_ will be an _error_ when running `citeproc-lua`

```
[...]
Database file #1: biblatex-examples.bib
.../scripts/citation-style-language/citeproc-latex-core.lua:218: attempt to concatenate a nil value (local 'style_name')
[...]
```

**Comment by zepinglee** [comment]
> If no style is defined we get the _warning_ message
> 
> ```
> Package citation-style-language Warning: Style name not specified.
> ```
> 
> which is okay. But it is more user-friendly if it could use a default style, apa or whatever:
> 
> ```
>     Package citation-style-language Warning: Style name not specified.
>     Will use default style apa ...
> ```

Thanks for your feedback and it makes sense.

> The problem is that the _warning_ will be an _error_ when running `citeproc-lua`
> 
> ```
> [...]
> Database file #1: biblatex-examples.bib
> .../scripts/citation-style-language/citeproc-latex-core.lua:218: attempt to concatenate a nil value (local 'style_name')
> [...]
> ```

Fixed in 7db1514.
