### ISSUE TITLE
Sorting the citations

### ISSUE THREAD

**Issue by hvoss49** [zepinglee/citeproc-lua#45]
**Describe the bug**
With two citations of the same year by the same author we get for example `<author>1988a, 1988b`
when using biblatex and an authoryear style. With `citation-style-language` we get it the other way round
(see screenshot)

**Additional information**
- TeX distribution: [TeX Live 2023, MacTeX 2023]
- Package `citation-style-language` version: [e.g. v0.4.4, main branch]
- LaTeX engine: [e.g. `lualatex`]

**To Reproduce**
```tex
\documentclass[]{article}
\usepackage{citation-style-language} 
\cslsetup{style=turabian-author-date} 
%\usepackage[style=authoryear]{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}

\cite{nietzsche:ksa,nietzsche:ksa1} 
\printbibliography

\end{document}
```

**Screenshots**

<img width="207" alt="Bildschirmfoto 2023-10-03 um 21 40 21" src="https://github.com/zepinglee/citeproc-lua/assets/12891199/06b9fc61-b13e-423f-9ef3-d1f1d674ffa9">

**Comment by hvoss49** [comment]
Ah, I See. The style `elsevier-harvard.csl` does it. But I am not familiar with XML so I can't use the code snippet for turabian.

**Comment by zepinglee** [comment]
> Ah, I See. The style `elsevier-harvard.csl` does it. But I am not familiar with XML so I can't use the code snippet for turabian.

This is my edit: <https://github.com/zepinglee/csl-styles/commit/bdbed1b3c53b6ce119044fdee80dceea309b2d7c>.

**Comment by hvoss49** [comment]
I am sorry, I can't get right. It is still "(Nietzsche 1988b, 1988a). Here are my files: https://hvoss.org/turabian.zip

**Comment by zepinglee** [comment]
> I am sorry, I can't get right. It is still "(Nietzsche 1988b, 1988a). Here are my files: https://hvoss.org/turabian.zip

Ah, my mistake. It turns out this is not easy to implement in CSL. I'll discuss with the CAL folks.

**Comment by zepinglee** [comment]
I post the issue at <https://discourse.citationstyles.org/t/sorting-citation-items-by-year-suffix/1830>.

**Comment by zepinglee** [comment]
Thanks to Sebastian Karcher's suggestion of adding citation sort `<key>`s identical to the ones in `<bibliography>`. Now the style works as expected (<https://gist.github.com/zepinglee/8a8355e465e4424cf7bd4a105da919a6>).

<img width="636" alt="Screenshot 2023-10-10 at 22 14 57" src="https://github.com/zepinglee/citeproc-lua/assets/12290822/6a710087-873f-4b5e-8f1a-fa99972a033d">

**Comment by hvoss49** [comment]
thanks, it is fine now!
