### ISSUE TITLE
\footcite command implementation needed

### ISSUE THREAD

**Issue by PunkFafa** [zepinglee/citeproc-lua#46]
How much time till the `\footcite` implementation? I need it so bad for my thesis. Thanks for all the hard work!

**Comment by zepinglee** [comment]
You can directly use `\cite` with a note style which actually creates a footnote. CSL's `\cite` is more like biblatex's `\autocite`. It chooses whether to use `\footnote` or not depending on the `class` (=`note`/`in-text`) attribute of the `<style>`.

BTW, `\footcite` is already added as an alias of `\cite`, though it might not be documented yet.

**Comment by bdarcus** [comment]
Yeah, FWIW, from the beginning, CSL was designed to be agnostic on output style, and so have the notion of automatic footnoting of relevant citations. It's similar to the biblatex autocite commands in that respect.

**Comment by CSDUMMI** [comment]
I've tried using a footnote style with this and it still showed the citations inline. Am I missing something?

**Comment by zepinglee** [comment]
> I've tried using a footnote style with this and it still showed the citations inline. Am I missing something?

Which version of the package are you using? Can you provide a minimal example as in the bug report issue template?
