### ISSUE TITLE
\l__csl_language_code_map_prop is not initiated corrected

### ISSUE THREAD

**Issue by josephwright** [zepinglee/citeproc-lua#54]
**Describe the bug**

`\l__csl_language_code_map_prop` is not initiated correctly, leading to an error with the latest `expl3` release. See e.g. https://tex.stackexchange.com/questions/709871/failed-to-compile-latex-document-citation-style-language

**Additional information**
- TeX distribution: TL'23
- Package `citation-style-language` version: {2023-10-05} {0.4.5}
- LaTeX engine: all

**To Reproduce**
```latex
\documentclass{article}
\usepackage{citation-style-language}

\begin{document}
\end{document}
```

**Comment by zepinglee** [comment]
Thanks for your report and fix!
