### ISSUE TITLE
OSCOLA: unexpected "nil" in footnote (type article-magazine)

### ISSUE THREAD

**Issue by daniel-eder** [zepinglee/citeproc-lua#58]
**Describe the bug**
The type article-magazine (and also article-journal) produces an unexpected "nil" in the footnote. The bibliography seems fine.

**Additional information**
- TeX distribution: MikTex 24.1 / MikTex Console 4.11 / LuaHBTeX 1.17.1
- Package `citation-style-language` version: 0.4.7
- LaTeX engine: `lualatex`

**To Reproduce**
https://github.com/daniel-eder/reproduce-oscola-csl-error

**Screenshots**
Screenshot from my generated pdf - notice the "nil" after "Analytics India Magazine"
![image](https://github.com/zepinglee/citeproc-lua/assets/1525711/ee62739e-f284-4d89-90d7-4f2353ad7b78)

Compared to the result from Zotero:
![image](https://github.com/zepinglee/citeproc-lua/assets/1525711/afaa9e58-51f0-4450-a662-6299c42fdd3d)

I am not sure which value citeproc-lua is missing and thus replacing with "nil". It is not the page number, I tried to add a page number in an additional citation (article-journal) and it prints the nil before the page number:
![image](https://github.com/zepinglee/citeproc-lua/assets/1525711/abf9e8be-1010-40c1-aa97-5515e5f19204)

**Comment by zepinglee** [comment]
Ah, this is because I forgot to consider empty `page` variable in 022f606. Fixed in 4c3eeb4.

**Comment by daniel-eder** [comment]
you are my saviour, thank you!

**Comment by daniel-eder** [comment]
Tested locally and works, thanks again
