### ISSUE TITLE
get rid of the title of the bibliography

### ISSUE THREAD

**Issue by whcjimmy** [zepinglee/citeproc-lua#62]
**Describe the bug**
I would like to remove the title of the bibliography. I tried ```\printbibliography[heading=none]```, but the title still exists. 

If my attempt is incorrect, is there a way to remove the title?

**Additional information**
- TeX distribution: [e.g. TeX Live 2022, MacTeX 2022, TeX Live 2022 on Overleaf]
- Package `citation-style-language` version: [e.g. v0.1.0, main branch]
- LaTeX engine: [e.g. `pdflatex` / `xelatex` / `lualatex`]

**To Reproduce**
```tex
\RequirePackage{filecontents}

\begin{filecontents*}{test.bib}
@article{acar2018survey,
  title={A survey on homomorphic encryption schemes: Theory and implementation},
  author={Acar, Abbas and Aksu, Hidayet and Uluagac, A Selcuk and Conti, Mauro},
  journal={ACM Computing Surveys (Csur)},
  volume={51},
  number={4},
  pages={1--35},
  year={2018},
  publisher={ACM New York, NY, USA}
}
\end{filecontents*}

\documentclass{article}         

% Customize Bibliography Style
\usepackage{citation-style-language}
\cslsetup{style = apa}
\addbibresource{test.bib}  % or example.bib or example.yaml

\begin{document}

\nocite{*}
\printbibliography[heading=none]

\end{document}
```

**Screenshots**
<img width="599" alt="image" src="https://github.com/zepinglee/citeproc-lua/assets/4002046/dd3e170c-a1c9-46e3-abf9-46d3af5a2f1e">

**Comment by whcjimmy** [comment]
I justed found out that ```[heading=none]``` is the parameter for biblatex. Therefore, I think my attempet is wrong.

**Comment by zepinglee** [comment]
This feature works as expected in v0.4.9.

<img width="797" alt="Screenshot 2024-04-26 at 20 21 18" src="https://github.com/zepinglee/citeproc-lua/assets/12290822/dadc4885-0ee9-4e81-b986-a02b14887b39">

**Comment by whcjimmy** [comment]
Thanks for your time. I successfully removed the title!
