### ISSUE TITLE
Ibid not working in chapter 2

### ISSUE THREAD

**Issue by nickw2066** [zepinglee/citeproc-lua#72]
**Describe the bug**
Ibid not appearing in citations in chapter 2. See the MWE below.

**Additional information**
- TeX distribution: MacTeX 2024
- Package `citation-style-language` version: v0.5.0
- LaTeX engine: `lualatex`

**To Reproduce**
```tex
\documentclass{book}

\begin{filecontents}[overwrite, noheader]{\jobname.json}
[
    {
        "id": "King2008-Gramma",
        "type": "thesis",
        "author": [
            {
                "family": "King",
                "given": "John T."
            }
        ],
        "title": "A Grammar of Dhimal",
        "title-short": "Grammar of Dhimal",
        "source": "PDF",
        "publisher-place": "Netherlands",
        "publisher": "Universiteit Leiden",
        "URL": "https://scholarlypublications.universiteitleiden.nl/handle/1887/13072",
        "genre": "doctoral dissertation",
        "issued": {
            "date-parts": [
                [
                    "2008",
                    "9",
                    "3"
                ]
            ]
        },
        "accessed": {
            "date-parts": [
                [
                    "2024",
                    "08",
                    "13"
                ]
            ]
        }
    }
]
\end{filecontents}

\usepackage{citation-style-language}
\cslsetup{style = chicago-fullnote-bibliography-with-ibid}
\addbibresource{\jobname.json}

\begin{document}

\chapter{Title1}

test cite1\cite{King2008-Gramma}
test cite2\cite{King2008-Gramma}

\chapter{Title2}

test cite3\cite{King2008-Gramma}
test cite4\cite{King2008-Gramma}

\end{document}
```

**Screenshots**
Chapter 1:
![Screenshot 2024-08-16 at 1 00 16 PM](https://github.com/user-attachments/assets/5a439c4b-8dde-46c0-9ec2-d898333e8171)
Chapter 2:
![Screenshot 2024-08-16 at 1 00 21 PM](https://github.com/user-attachments/assets/7e5a6b01-6ed8-4ffa-beab-968735467699)

Style file from [https://www.zotero.org/styles?q=chicago](https://www.zotero.org/styles?q=chicago).

**Comment by zepinglee** [comment]
Thanks for your report and I can reproduce it. The second note in chapter 2 should be "ibid."

What about the first note in chapter 2? Should it be in the long form (`position="first"`) or short form(`position="subsequent"`)? I've checked the same notes with `biblatex-chicago` and `verbose-ibid` styles. Both them choose short forms but I doubt that is correct for typical note styles.

```latex
\documentclass{book}

\begin{filecontents}[overwrite, noheader]{\jobname.bib}
@phdthesis{King2008-Gramma,
  title = {A Grammar of {Dhimal}},
  shorttitle = {Grammar of {Dhimal}},
  author = {King, John T.},
  year = {2008},
  month = sep,
  address = {Netherlands},
  url = {https://scholarlypublications.universiteitleiden.nl/handle/1887/13072},
  urldate = {2024-08-13},
  type = {doctoral dissertation},
  school = {Universiteit Leiden}
}
\end{filecontents}

\usepackage[notes, useibid=true]{biblatex-chicago}
% \usepackage[style=verbose-ibid]{biblatex}
\addbibresource{\jobname.bib}


\begin{document}

\chapter{Title1}
test cite1\footcite{King2008-Gramma}
test cite2\footcite{King2008-Gramma}

\chapter{Title2}
test cite3\footcite{King2008-Gramma}
test cite4\footcite{King2008-Gramma}

\end{document}
```

Chapter 2:
<img width="364" alt="Screenshot 2024-08-17 at 16 13 21" src="https://github.com/user-attachments/assets/5121e251-b712-43a0-944d-dd77e1dc288b">

**Comment by nickw2066** [comment]
￼Turabian (from Everand.com <http://everand.com/>) says:
￼

I assume Chicago is similar.

**Comment by zepinglee** [comment]
> ￼Turabian (from Everand.com <http://everand.com/>) says: ￼ I assume Chicago is similar.
> […](#)

The contents replied via email are not displayed correctly. Can you please post it again via GitHub website?

**Comment by zepinglee** [comment]
It looks more reasonable to me that for first note in chapter 2 is in full form (`position="first"`). In CSL style, a subsequent citation of an item is assumed to have a `first-reference-note-number` variable which can be outputted like "supra note #". This note number doesn't make sense if it appears at the beginning of chapter 2.

The biblatex style `verbose-inote` is similar to this. The following LaTeX code produces "King, see n. 1." in footnote 1, which is difficult for readers to understand. Biblatex has a `citereset` option which can force a full citation at the beginning of a new chapter.

<img width="286" alt="Screenshot 2024-08-19 at 20 07 59" src="https://github.com/user-attachments/assets/10114111-dc1a-45b5-ba5d-349771aad993">

With `citereset=chapter`:
<img width="614" alt="Screenshot 2024-08-19 at 20 11 29" src="https://github.com/user-attachments/assets/8ec1a43c-8897-4024-b41d-bbaafba43685">



```latex
\documentclass{book}

\begin{filecontents}[overwrite, noheader]{\jobname.bib}
@phdthesis{King2008-Gramma,
  title = {A Grammar of {Dhimal}},
  shorttitle = {Grammar of {Dhimal}},
  author = {King, John T.},
  year = {2008},
  month = sep,
  address = {Netherlands},
  url = {https://scholarlypublications.universiteitleiden.nl/handle/1887/13072},
  urldate = {2024-08-13},
  type = {doctoral dissertation},
  school = {Universiteit Leiden}
}
\end{filecontents}

\usepackage[style=verbose-inote]{biblatex}
% \usepackage[style=verbose-inote, citereset=chapter]{biblatex}
\addbibresource{\jobname.bib}


\begin{document}

\chapter{Title1}
% \footnote{Foo}
test cite1\footcite{King2008-Gramma}
test cite2\footcite{King2008-Gramma}

\chapter{Title2}
test cite3\footcite{King2008-Gramma}
test cite4\footcite{King2008-Gramma}
\footnote{Foo}
test cite4\footcite{King2008-Gramma}

\end{document}
```

**Comment by nickw2066** [comment]
That sounds good.

The pictures which didn't come through in my email reply (above) are:
![Screenshot 2024-08-18 at 2 49 37 PM](https://github.com/user-attachments/assets/5746bbae-e6b6-449b-a091-ad78aad406fd)
![Screenshot 2024-08-18 at 2 49 51 PM](https://github.com/user-attachments/assets/70d4fa81-fbdd-45b9-ab4a-d4f9fb891017)
