### ISSUE TITLE
Dash for repeating author list

### ISSUE THREAD

**Issue by harrysw1729** [zepinglee/citeproc-lua#76]
If an entry's author list is identical to the preceding entry's, the author list would be replaced by a dash. My question is whether there is any way to turn off the dash similar to the `dashed=false` option in biblatex?

Thank you very much for your help!

Below is a minimal example for replicating the dash.

```latex
\begin{filecontents}[overwrite]{references.bib}
@article{hassin1997equilibrium,
  title={Equilibrium threshold strategies: The case of queues with priorities},
  author={Hassin, Refael and Haviv, Moshe},
  journal={Operations Research},
  year={1997},
  publisher={INFORMS},
  doi={10.1287/opre.45.6.966}
}

@book{hassin2003queue,
  title={To queue or not to queue: Equilibrium behavior in queueing systems},
  author={Hassin, Refael and Haviv, Moshe},
  year={2003},
  publisher={Springer},
  isbn={9781402072031}
}
\end{filecontents}

\documentclass{article}
\usepackage[style=chicago-author-date]{citation-style-language}
\addbibresource{references.bib}

\begin{document}
\cite{hassin1997equilibrium,hassin2003queue}

\printbibliography{}
\end{document}

```

Here is the screenshot of the bibliography:

<img width="421" alt="image" src="https://github.com/user-attachments/assets/07d1264d-64b2-4d7e-b8d5-5c146b921a93">

**Comment by zepinglee** [comment]
Which is the CSL style?

**Comment by harrysw1729** [comment]
> Which is the CSL style?

Thanks for the reply! It was `chicago-author-date`, which comes with the package.

I have edited my post to include a minimal example to replicate the scenario.

**Comment by zepinglee** [comment]
The three dashes are specified in the Chicago Manual of Style. You may remove the `subsequent-author-substitute="&#8212;&#8212;&#8212;"` attribute in the `<bibliography>` element to disable this behavior (see also the CSL [spec](https://docs.citationstyles.org/en/stable/specification.html#reference-grouping)).

https://github.com/zepinglee/citeproc-lua/blob/72aac3001738e752611c443a2da08ccbb9c1da96/submodules/styles/chicago-author-date.csl#L678

I don't think it's good design to add an LaTeX option to control this behavior though technically it's possible.

**Comment by harrysw1729** [comment]
> The three dashes are specified in the Chicago Manual of Style. You may remove the `subsequent-author-substitute="&#8212;&#8212;&#8212;"` attribute in the `<bibliography>` element to disable this behavior (see also the CSL [spec](https://docs.citationstyles.org/en/stable/specification.html#reference-grouping)).
> 
> https://github.com/zepinglee/citeproc-lua/blob/72aac3001738e752611c443a2da08ccbb9c1da96/submodules/styles/chicago-author-date.csl#L678
> 
> I don't think it's good design to add an LaTeX option to control this behavior though technically it's possible.

Was wondering whether this was a CSL-related issue. Thanks for locating the relevant attribute!

**Comment by zepinglee** [comment]
The three dashes are specified in Chicago Manual of Style.

<img width="595" alt="Screenshot 2024-09-04 at 08 26 39" src="https://github.com/user-attachments/assets/8fec0b28-ed15-40eb-9add-75d6533cde11">
