### ISSUE TITLE
Zotero integration

### ISSUE THREAD

**Issue by simifilm** [zepinglee/citeproc-lua#8]
I understand that `CSL` is not constrained to `Zotero`, still I wonder whether some kind of integration is planned. I am merely thinking of two areas:

- Accessing `Zotero` bibliographic data. This would massively facilitate the ability to use the same data with different tools/writing apps.

- Accessing the CSL styles installed by `Zotero`. This would eliminate the need to have all auxiliary files installed two times.

**Comment by zepinglee** [comment]
1. Do you mean accessing the sqlite database of Zotero? The internal types and fields in Zotero are different from CSL-JSON (see <https://aurimasv.github.io/z2csl/typeMap.xml>) and a conversion is needed before feeding the data to a citeproc engine. 
2. It's a good idea and I'll add it. The style files of Zotero are stored in the "Zotero Data Directory" which is `~/Zotero` by default and the user may set a custom path (e.g., `\cslsetup{zotero-path = /somewhere/else`).

**Comment by simifilm** [comment]
Yes, I mean the sqlite database.

**Comment by zepinglee** [comment]
> Yes, I mean the sqlite database.

It sounds great but it may take some time to implement.

**Comment by bdarcus** [comment]
I wonder if that would be better as a separate project?

**Comment by EmmanuelCharpentier** [comment]
FWIW : [Eric Hetzner](https://github.com/egh) has already implemented a common [base](https://github.com/egh/zotxt) allowing various tools to interact with Zotero from [emacs](https://github.com/egh/zotxt-emacs), and [pandoc](https://github.com/odkr/pandoc-zotxt.lua) so far...

There is no common framework for using these tools, that seriously lack end-user (=idiot-) level documentation. Some thought is needed to integrate them in, say, emacs' AUCTeX, Org or pandoc-mode (as well as other editors...).

The interaction via the Zotero database envisioned by [simifilm](https://github.com/simifilm) should probably use [zotxt](https://github.com/egh/zotxt), thus avoiding touching the (non-documented) sqlite base and using the (published) API. Better safe than sorry...

I like the idea to be able to use Zotero data and CSL styles in other tools than the damn "word processors" that the corporate world afflicts us with...
